### ISSUE TITLE
can't get it working

### ISSUE THREAD

**Issue by hymie0** [8ware/task-dashboard#1]
I've never used tmux before this, so that's part of my problem.

    tmux 1.9a
    task 2.5.1 built for linux

This line

        tmux('set', '-t', "$session:$window", 'status', "off");

gives error

> session not found: task-dashboard:view

Based on the tmux man page, I changed that to

        tmux('set', '-t', "$session", 'status', "off");

That fixed one error.  But I still get lots of errors

> can't find pane: %0
> can't find pane: %1
> can't find pane: %1
> can't find pane: %2
> can't find pane: %3
> can't find pane: %4
> can't find pane: %5

and I end up with just a blank screen with nothing on it.  Apparently I'm at a (null) shell prompt, becuase ^D returns me to my shell.

    tmux list-panes
    0: [123x44] [history 0/2000, 0 bytes] %0 (active)

So it looks like my panes aren't being created, and they don't have a % sign in the name/number?

Yes, changing every instance of %$ (where $ is the start of the varibale holding the pane number) to just $ fixed the problem.

So it's working after those changes.   Now I need to learn how to make the panes smaller so they fit on my screen.

**Comment by 8ware** [comment]
Hey, thanks for the hint. It seems that I already came across that issue a while ago and fixed it locally like you did (by removing the `%`-signs). The fix is committed now.

You can resize the panes either in tmux directly (using `<prefix>`+`Alt`+`Left`/`Right`) or by changing the task-dashboard's configuration file. The layout syntax is described in the README. Let me know if the description is not expressive enough.
